### ISSUE TITLE
2018-03-26 

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/comicsrss.com#66]
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND www.gocomics.com www.gocomics.com:80
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
```

Did I get blocked? :( I guess it becomes more and more likely the more popular this becomes.

**Comment by ArtskydJ** [comment]
This was a one-time error...
