### ISSUE TITLE
Handle http errors better

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/comicsrss.com#72]
Sometimes I get this error:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:200:15)
    at Socket.socketOnEnd (_http_client.js:292:23)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

I want to at least know what error this is. I think it is a network connectivity error.

I can either restart the entire build when this happens, or I can handle the error. Handling the error is a much more elegant solution to this specific issue.

**Comment by ArtskydJ** [comment]
Similar issue (Aug 10, 1:27 AM)
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND www.gocomics.com www.gocomics.com:443
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
```

**Comment by ArtskydJ** [comment]
Another similar issue (Sep 29, 1:39 AM)

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TLSWrap.onread (net.js:552:26)
```

**Comment by ArtskydJ** [comment]
I've been pretty happy with error handling for a while now. I forget which change(s) fixed it.
