### ISSUE TITLE
Build is failing...

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/comicsrss.com#77]
here is the problem...
https://raw.githubusercontent.com/ArtskydJ/comicsrss.com/gh-pages/_generator/tmp/_comic-objects.json

```json
				...
				date": "2018-05-09",
				"comicImageUrl": "http://assets.amuniversal.com/3863ed702ed201362e6d005056a9545d"
			}
		]
	},
	null, /* ********** HERE IS THE PROBLEM ********** */
	{
		"titleAndAuthor": "Ozy and Millie by Dana Simpson",
		"basename": "ozy-and-millie",
		"author": "Dana Simpson",
		...
```

if that null value is removed then it should work...

I get this error when I run `node generator/index`

```
root@josephdykstra:~/comicsrss.com/_generator# sh generate-and-push.sh
https://www.gocomics.com/owlturd 302 error
/root/comicsrss.com/_generator/generator/generate-main-page-from-comic-objects.js:17
                ].indexOf(comicObject.basename) !== -1
                                     ^

TypeError: Cannot read property 'basename' of null
    at /root/comicsrss.com/_generator/generator/generate-main-page-from-comic-objects.js:17:24
    at Array.filter (native)
    at generateMainPage (/root/comicsrss.com/_generator/generator/generate-main-page-from-comic-objects.js:9:43)
    at writeFilesFromComicObjects (/root/comicsrss.com/_generator/generator/index.js:9:21)
    at Object.<anonymous> (/root/comicsrss.com/_generator/generator/index.js:28:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

```

Should be an easy fix...

**Comment by ArtskydJ** [comment]
Fixed in https://github.com/ArtskydJ/comicsrss.com/commit/1947c17415836a4d12925aaec272c1d83238693e
